// <auto-generated />
using System;
using KoiFarmShop.Repositories.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KoiFarmShop.Repositories.Migrations
{
    [DbContext(typeof(KoiFarmDbContext))]
    partial class KoiFarmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.CareService", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("KoiId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServicePrice")
                        .HasColumnType("int");

                    b.HasKey("ServiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("KoiId");

                    b.ToTable("CareServices");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            CustomerId = 1,
                            KoiId = 1,
                            ServiceDesc = "Chăm sóc cá Koi tiêu chuẩn",
                            ServicePrice = 150000
                        },
                        new
                        {
                            ServiceId = 2,
                            CustomerId = 2,
                            KoiId = 2,
                            ServiceDesc = "Chăm sóc cá Koi nâng cao",
                            ServicePrice = 200000
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            CartId = 1,
                            CustomerId = 1
                        },
                        new
                        {
                            CartId = 2,
                            CustomerId = 2
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("KoiId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityPerBatch")
                        .HasColumnType("int");

                    b.Property<int>("QuantityPerKoi")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("KoiId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            CartId = 1,
                            DateAdded = new DateTime(2026, 3, 27, 16, 24, 13, 172, DateTimeKind.Local).AddTicks(9796),
                            KoiId = 1,
                            QuantityPerBatch = 1,
                            QuantityPerKoi = 2
                        },
                        new
                        {
                            CartItemId = 2,
                            CartId = 2,
                            DateAdded = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(92),
                            KoiId = 2,
                            QuantityPerBatch = 2,
                            QuantityPerKoi = 3
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.ConsignmentKoi", b =>
                {
                    b.Property<int>("ConsignmentKoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgreedPrice")
                        .HasColumnType("int");

                    b.Property<int?>("ConsignmentRequestRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("KoiId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ConsignmentKoiId");

                    b.HasIndex("ConsignmentRequestRequestId");

                    b.HasIndex("KoiId");

                    b.ToTable("ConsignmentKois");

                    b.HasData(
                        new
                        {
                            ConsignmentKoiId = 1,
                            AgreedPrice = 150000,
                            EndDate = new DateTime(2026, 9, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(2402),
                            KoiId = 1,
                            RequestId = 1,
                            StartDate = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(2305)
                        },
                        new
                        {
                            ConsignmentKoiId = 2,
                            AgreedPrice = 200000,
                            EndDate = new DateTime(2027, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(2692),
                            KoiId = 2,
                            RequestId = 2,
                            StartDate = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(2691)
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.ConsignmentRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CareService")
                        .HasColumnType("bit");

                    b.Property<string>("Certificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ConsignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConsignmentDuration")
                        .HasColumnType("int");

                    b.Property<int>("ConsignmentFee")
                        .HasColumnType("int");

                    b.Property<string>("ConsignmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("KoiAge")
                        .HasColumnType("int");

                    b.Property<string>("KoiBreed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KoiImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KoiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KoiSize")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ConsignmentRequests");

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            CareService = false,
                            Certificate = "Giấy chứng nhận 001",
                            ConsignmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConsignmentDuration = 0,
                            ConsignmentFee = 50000,
                            ConsignmentType = "Bán",
                            CustomerId = 1,
                            KoiAge = 0,
                            KoiSize = 0.0,
                            Notes = "Yêu cầu bán cá Koi loại A",
                            RequestDate = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(1296),
                            Status = "Đang xử lý"
                        },
                        new
                        {
                            RequestId = 2,
                            CareService = false,
                            Certificate = "Giấy chứng nhận 002",
                            ConsignmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConsignmentDuration = 0,
                            ConsignmentFee = 70000,
                            ConsignmentType = "Chăm sóc",
                            CustomerId = 2,
                            KoiAge = 0,
                            KoiSize = 0.0,
                            Notes = "Chăm sóc cá Koi loại B",
                            RequestDate = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(1934),
                            Status = "Hoàn thành"
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Đường ABC, Quận 1",
                            CustomerName = "Sang Yoon Jin",
                            Email = "giakhanhngo1503@gmail.com",
                            Phone = "0123456789",
                            Points = 100,
                            RegistrationDate = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(773),
                            UserId = 3
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "456 Đường DEF, Quận 2",
                            CustomerName = "Yến Di",
                            Email = "yendi1907@gmai.com",
                            Phone = "0987654321",
                            Points = 200,
                            RegistrationDate = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(1050),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FeedbackDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("KoiId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("KoiId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            FeedbackId = 1,
                            Comment = "Cá Koi đẹp và khỏe mạnh",
                            CustomerId = 1,
                            FeedbackDate = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(3423),
                            KoiId = 1,
                            Rating = 5
                        },
                        new
                        {
                            FeedbackId = 2,
                            Comment = "Dịch vụ chăm sóc tốt, nhưng giao hàng chậm",
                            CustomerId = 2,
                            FeedbackDate = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(3692),
                            KoiId = 2,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.KoiCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("KoiCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDesc = "Koi Kohaku thân đỏ trắng là dòng cá tiêu biểu, khả năng sinh sôi nảy nở cực tốt và cũng là 1 trong những dòng cá có tuổi thọ cao.",
                            CategoryName = "Koi Kohaku"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDesc = "Koi Karashi loại cá Koi này có da trơn màu sắc từ màu vàng nhạt đến vàng đậm toàn thân, rất đẹp và tươi tắn.",
                            CategoryName = "Koi Karashi"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDesc = "Koi Showa là dòng Gosanke,Showa hấp dẫn người chơi bởi 3 màu đen-đỏ-trắng. Trong đó, màu trắng(Shiroji) là màu nền, tiếp theo là màu đỏ(Hi) và màu đen(Sumi).",
                            CategoryName = "Koi Showa"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDesc = "Koi Asagi có màu xám bạc, chính giữa có vẩy đen, ngoài bìa mỗi vẩy hơi xanh dậm da trời, nhìn như lưới cá Fukurin.Nửa phần dưới bụng cá là màu cam.",
                            CategoryName = "Koi Asagi"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryDesc = "Koi Shusui tạo cảm giác mạnh từ 3 màu đen, đỏ, trắng tương phản cùng với 2 dải vảy đen nháy cùng màu đối xứng lợp mái ấn tượng trên sống lưng.",
                            CategoryName = "Koi Shusui"
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.KoiFish", b =>
                {
                    b.Property<int>("KoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Awards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BreedType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DailyFeed")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KoiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PricePerBatch")
                        .HasColumnType("int");

                    b.Property<int>("PricePerKoi")
                        .HasColumnType("int");

                    b.Property<decimal>("ScreeningRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<float>("Size")
                        .HasColumnType("real");

                    b.HasKey("KoiId");

                    b.HasIndex("CategoryId");

                    b.ToTable("KoiFishs");

                    b.HasData(
                        new
                        {
                            KoiId = 1,
                            Age = 3,
                            Awards = "Giải nhất",
                            BreedType = "Nhập khẩu",
                            CategoryId = 1,
                            DailyFeed = 200,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Kohaku1.jpg",
                            KoiName = "Koi Kohaku 1",
                            Origin = "Việt Nam",
                            Personality = "Hiền hòa",
                            PricePerBatch = 7500000,
                            PricePerKoi = 1500000,
                            ScreeningRate = 95.5m,
                            Size = 30f
                        },
                        new
                        {
                            KoiId = 2,
                            Age = 4,
                            Awards = "Giải nhì",
                            BreedType = "Thuần Việt",
                            CategoryId = 1,
                            DailyFeed = 250,
                            Gender = "Đực",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Kohaku2.jpg",
                            KoiName = "Koi Kohaku 2",
                            Origin = "Nhật Bản",
                            Personality = "Hiền hòa",
                            PricePerBatch = 8000000,
                            PricePerKoi = 1600000,
                            ScreeningRate = 96.0m,
                            Size = 32f
                        },
                        new
                        {
                            KoiId = 3,
                            Age = 2,
                            Awards = "Giải ba",
                            BreedType = "Thuần Việt",
                            CategoryId = 1,
                            DailyFeed = 180,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Kohaku3.jpg",
                            KoiName = "Koi Kohaku 3",
                            Origin = "Việt Nam",
                            Personality = "Chủ động",
                            PricePerBatch = 7000000,
                            PricePerKoi = 1400000,
                            ScreeningRate = 94.0m,
                            Size = 28f
                        },
                        new
                        {
                            KoiId = 4,
                            Age = 5,
                            Awards = "Giải nhất",
                            BreedType = "Lai F1",
                            CategoryId = 1,
                            DailyFeed = 300,
                            Gender = "Đực",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Kohaku4 .jpg",
                            KoiName = "Koi Kohaku 4",
                            Origin = "Nhật Bản",
                            Personality = "Chủ động",
                            PricePerBatch = 8500000,
                            PricePerKoi = 1700000,
                            ScreeningRate = 98.0m,
                            Size = 35f
                        },
                        new
                        {
                            KoiId = 5,
                            Age = 3,
                            Awards = "Giải nhì",
                            BreedType = "Thuần Việt",
                            CategoryId = 1,
                            DailyFeed = 220,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Kohaku5.jpg",
                            KoiName = "Koi Kohaku 5",
                            Origin = "Việt Nam",
                            Personality = "Hiền hòa",
                            PricePerBatch = 7500000,
                            PricePerKoi = 1500000,
                            ScreeningRate = 96.5m,
                            Size = 30f
                        },
                        new
                        {
                            KoiId = 6,
                            Age = 2,
                            Awards = "Giải ba",
                            BreedType = "Lai F1",
                            CategoryId = 2,
                            DailyFeed = 210,
                            Gender = "Đực",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Koi Karashi 1.jpg",
                            KoiName = "Koi Karashi 1",
                            Origin = "Việt Nam",
                            Personality = "Chủ động",
                            PricePerBatch = 6500000,
                            PricePerKoi = 1300000,
                            ScreeningRate = 94.5m,
                            Size = 28f
                        },
                        new
                        {
                            KoiId = 7,
                            Age = 3,
                            Awards = "Giải nhất",
                            BreedType = "Thuần Việt",
                            CategoryId = 2,
                            DailyFeed = 230,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Koi Karashi2.jpg",
                            KoiName = "Koi Karashi 2",
                            Origin = "Nhật Bản",
                            Personality = "Hiền hòa",
                            PricePerBatch = 7000000,
                            PricePerKoi = 1400000,
                            ScreeningRate = 95.5m,
                            Size = 30f
                        },
                        new
                        {
                            KoiId = 8,
                            Age = 2,
                            Awards = "Giải nhì",
                            BreedType = "Lai F1",
                            CategoryId = 2,
                            DailyFeed = 190,
                            Gender = "Đực",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Koi Karashi 3.jpg",
                            KoiName = "Koi Karashi 3",
                            Origin = "Việt Nam",
                            Personality = "Chủ động",
                            PricePerBatch = 6750000,
                            PricePerKoi = 1350000,
                            ScreeningRate = 94.0m,
                            Size = 27f
                        },
                        new
                        {
                            KoiId = 9,
                            Age = 4,
                            Awards = "Giải ba",
                            BreedType = "Thuần Việt",
                            CategoryId = 2,
                            DailyFeed = 240,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Koi Karashi 4.jpg",
                            KoiName = "Koi Karashi 4",
                            Origin = "Nhật Bản",
                            Personality = "Hiền hòa",
                            PricePerBatch = 7250000,
                            PricePerKoi = 1450000,
                            ScreeningRate = 96.0m,
                            Size = 32f
                        },
                        new
                        {
                            KoiId = 10,
                            Age = 5,
                            Awards = "Giải nhất",
                            BreedType = "Nhập khẩu",
                            CategoryId = 2,
                            DailyFeed = 300,
                            Gender = "Đực",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Koi Karashi 5 .jpg",
                            KoiName = "Koi Karashi 5",
                            Origin = "Việt Nam",
                            Personality = "Chủ động",
                            PricePerBatch = 7500000,
                            PricePerKoi = 1500000,
                            ScreeningRate = 97.5m,
                            Size = 35f
                        },
                        new
                        {
                            KoiId = 11,
                            Age = 3,
                            Awards = "Giải ba",
                            BreedType = "Thuần Việt",
                            CategoryId = 3,
                            DailyFeed = 210,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Showa 1.jpg",
                            KoiName = "Koi Showa 1",
                            Origin = "Việt Nam",
                            Personality = "Hiền hòa",
                            PricePerBatch = 7000000,
                            PricePerKoi = 1400000,
                            ScreeningRate = 95.0m,
                            Size = 33f
                        },
                        new
                        {
                            KoiId = 12,
                            Age = 4,
                            Awards = "Giải nhì",
                            BreedType = "Nhập khẩu",
                            CategoryId = 3,
                            DailyFeed = 250,
                            Gender = "Đực",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Showa2.jpg",
                            KoiName = "Koi Showa 2",
                            Origin = "Nhật Bản",
                            Personality = "Chủ động",
                            PricePerBatch = 7250000,
                            PricePerKoi = 1450000,
                            ScreeningRate = 96.0m,
                            Size = 35f
                        },
                        new
                        {
                            KoiId = 13,
                            Age = 2,
                            Awards = "Giải nhất",
                            BreedType = "Lai F1",
                            CategoryId = 3,
                            DailyFeed = 200,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Showa 3.jpg",
                            KoiName = "Koi Showa 3",
                            Origin = "Việt Nam",
                            Personality = "Hiền hòa",
                            PricePerBatch = 6750000,
                            PricePerKoi = 1350000,
                            ScreeningRate = 94.5m,
                            Size = 30f
                        },
                        new
                        {
                            KoiId = 14,
                            Age = 3,
                            Awards = "Giải ba",
                            BreedType = "Thuần Việt",
                            CategoryId = 3,
                            DailyFeed = 220,
                            Gender = "Đực",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Showa 4.jpg",
                            KoiName = "Koi Showa 4",
                            Origin = "Nhật Bản",
                            Personality = "Chủ động",
                            PricePerBatch = 7500000,
                            PricePerKoi = 1500000,
                            ScreeningRate = 96.5m,
                            Size = 32f
                        },
                        new
                        {
                            KoiId = 15,
                            Age = 4,
                            Awards = "Giải nhất",
                            BreedType = "Thuần Việt",
                            CategoryId = 3,
                            DailyFeed = 260,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Showa5.jpg",
                            KoiName = "Koi Showa 5",
                            Origin = "Việt Nam",
                            Personality = "Hiền hòa",
                            PricePerBatch = 7750000,
                            PricePerKoi = 1550000,
                            ScreeningRate = 97.0m,
                            Size = 34f
                        },
                        new
                        {
                            KoiId = 16,
                            Age = 3,
                            Awards = "Giải ba",
                            BreedType = "Nhập khẩu",
                            CategoryId = 4,
                            DailyFeed = 210,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Asagi 1.jpg",
                            KoiName = "Koi Asagi 1",
                            Origin = "Việt Nam",
                            Personality = "Hiền hòa",
                            PricePerBatch = 7250000,
                            PricePerKoi = 1450000,
                            ScreeningRate = 95.0m,
                            Size = 31f
                        },
                        new
                        {
                            KoiId = 17,
                            Age = 4,
                            Awards = "Giải nhì",
                            BreedType = "Thuần Việt",
                            CategoryId = 4,
                            DailyFeed = 240,
                            Gender = "Đực",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Asagi 2.jpg",
                            KoiName = "Koi Asagi 2",
                            Origin = "Nhật Bản",
                            Personality = "Chủ động",
                            PricePerBatch = 7500000,
                            PricePerKoi = 1500000,
                            ScreeningRate = 96.0m,
                            Size = 34f
                        },
                        new
                        {
                            KoiId = 18,
                            Age = 2,
                            Awards = "Giải nhất",
                            BreedType = "Thuần Việt",
                            CategoryId = 4,
                            DailyFeed = 200,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Asagi 3.jpg",
                            KoiName = "Koi Asagi 3",
                            Origin = "Việt Nam",
                            Personality = "Hiền hòa",
                            PricePerBatch = 7000000,
                            PricePerKoi = 1400000,
                            ScreeningRate = 94.5m,
                            Size = 29f
                        },
                        new
                        {
                            KoiId = 19,
                            Age = 3,
                            Awards = "Giải ba",
                            BreedType = "Lai F1",
                            CategoryId = 4,
                            DailyFeed = 220,
                            Gender = "Đực",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Asagi 4.jpg",
                            KoiName = "Koi Asagi 4",
                            Origin = "Nhật Bản",
                            Personality = "Chủ động",
                            PricePerBatch = 7250000,
                            PricePerKoi = 1450000,
                            ScreeningRate = 95.5m,
                            Size = 32f
                        },
                        new
                        {
                            KoiId = 20,
                            Age = 4,
                            Awards = "Giải nhất",
                            BreedType = "Nhập khẩu",
                            CategoryId = 4,
                            DailyFeed = 250,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Asagi5.jpg",
                            KoiName = "Koi Asagi 5",
                            Origin = "Việt Nam",
                            Personality = "Hiền hòa",
                            PricePerBatch = 7500000,
                            PricePerKoi = 1500000,
                            ScreeningRate = 96.5m,
                            Size = 36f
                        },
                        new
                        {
                            KoiId = 21,
                            Age = 3,
                            Awards = "Giải ba",
                            BreedType = "Nhập khẩu",
                            CategoryId = 5,
                            DailyFeed = 220,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Shusui1.jpg",
                            KoiName = "Koi Shusui 1",
                            Origin = "Việt Nam",
                            Personality = "Hiền hòa",
                            PricePerBatch = 7000000,
                            PricePerKoi = 1400000,
                            ScreeningRate = 95.0m,
                            Size = 30f
                        },
                        new
                        {
                            KoiId = 22,
                            Age = 4,
                            Awards = "Giải nhì",
                            BreedType = "Lai F1",
                            CategoryId = 5,
                            DailyFeed = 240,
                            Gender = "Đực",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Shusui 2.jpg",
                            KoiName = "Koi Shusui 2",
                            Origin = "Nhật Bản",
                            Personality = "Chủ động",
                            PricePerBatch = 7500000,
                            PricePerKoi = 1500000,
                            ScreeningRate = 96.0m,
                            Size = 33f
                        },
                        new
                        {
                            KoiId = 23,
                            Age = 2,
                            Awards = "Giải nhất",
                            BreedType = "Thuần Việt",
                            CategoryId = 5,
                            DailyFeed = 200,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Shusui 3.jpg",
                            KoiName = "Koi Shusui 3",
                            Origin = "Việt Nam",
                            Personality = "Hiền hòa",
                            PricePerBatch = 6750000,
                            PricePerKoi = 1350000,
                            ScreeningRate = 94.5m,
                            Size = 28f
                        },
                        new
                        {
                            KoiId = 24,
                            Age = 3,
                            Awards = "Giải ba",
                            BreedType = "Thuần Việt",
                            CategoryId = 5,
                            DailyFeed = 210,
                            Gender = "Đực",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Shusui 4.jpg",
                            KoiName = "Koi Shusui 4",
                            Origin = "Nhật Bản",
                            Personality = "Chủ động",
                            PricePerBatch = 7000000,
                            PricePerKoi = 1400000,
                            ScreeningRate = 95.0m,
                            Size = 31f
                        },
                        new
                        {
                            KoiId = 25,
                            Age = 4,
                            Awards = "Giải nhất",
                            BreedType = "Thuần Việt",
                            CategoryId = 5,
                            DailyFeed = 250,
                            Gender = "Mái",
                            HealthStatus = "Khỏe mạnh",
                            ImageURL = "/images/Shusui5 .jpg",
                            KoiName = "Koi Shusui 5",
                            Origin = " Việt Nam",
                            Personality = "Hiền hòa",
                            PricePerBatch = 7500000,
                            PricePerKoi = 1500000,
                            ScreeningRate = 96.5m,
                            Size = 34f
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KoiId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityPerBatch")
                        .HasColumnType("int");

                    b.Property<int>("QuantityPerKoi")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("KoiId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PromotionId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            KoiId = 1,
                            OrderId = 1,
                            PaymentMethod = "Chuyển khoản",
                            PromotionId = 1,
                            QuantityPerBatch = 1,
                            QuantityPerKoi = 3,
                            ShippingAddress = "123 Main St",
                            Status = "Đang xử lý",
                            TotalAmount = 0
                        },
                        new
                        {
                            OrderDetailId = 2,
                            KoiId = 2,
                            OrderId = 2,
                            PaymentMethod = "Thanh toán khi nhận hàng",
                            PromotionId = 2,
                            QuantityPerBatch = 1,
                            QuantityPerKoi = 2,
                            ShippingAddress = "456 Second St",
                            Status = "Đã giao",
                            TotalAmount = 0
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Orders", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StaffId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(8332),
                            StaffId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 3, 26, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(8642),
                            StaffId = 2
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromotionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PromotionId");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            PromotionId = 1,
                            Description = "Giảm giá 10% cho tất cả các sản phẩm trong mùa hè.",
                            DiscountRate = 0.10m,
                            EndDate = new DateTime(2026, 4, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(9254),
                            PromotionName = "Khuyến mãi mùa hè",
                            StartDate = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(9159)
                        },
                        new
                        {
                            PromotionId = 2,
                            Description = "Giảm giá 15% cho các đơn hàng trên 5 triệu.",
                            DiscountRate = 0.15m,
                            EndDate = new DateTime(2026, 4, 6, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(9445),
                            PromotionName = "Khuyến mãi Tết Nguyên Đán",
                            StartDate = new DateTime(2026, 3, 17, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(9441)
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCustomers")
                        .HasColumnType("int");

                    b.Property<int>("TotalRevenue")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            ReportDate = new DateTime(2026, 3, 27, 16, 24, 13, 173, DateTimeKind.Local).AddTicks(9727),
                            Summary = "Doanh thu tháng này tăng 10% so với tháng trước.",
                            TotalCustomers = 100,
                            TotalRevenue = 5000000
                        },
                        new
                        {
                            ReportId = 2,
                            ReportDate = new DateTime(2026, 2, 27, 16, 24, 13, 174, DateTimeKind.Local).AddTicks(92),
                            Summary = "Doanh thu tháng trước ổn định.",
                            TotalCustomers = 80,
                            TotalRevenue = 4500000
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("StaffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.HasIndex("UserId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            Email = "dihny5348@ut.edu.vn",
                            JoinDate = new DateTime(2024, 3, 27, 16, 24, 13, 171, DateTimeKind.Local).AddTicks(6343),
                            Phone = "0905681918",
                            Role = "Quản lý",
                            Salary = 20000000,
                            StaffName = "Ngô Gia Khánh",
                            UserId = 1
                        },
                        new
                        {
                            StaffId = 2,
                            Email = "Khanhng5776@ut.edu.vn",
                            JoinDate = new DateTime(2025, 3, 27, 16, 24, 13, 172, DateTimeKind.Local).AddTicks(7812),
                            Phone = "0344883755",
                            Role = "Nhân viên bán hàng",
                            Salary = 15000000,
                            StaffName = "Huỳnh Ngô Yến Di",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHasher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "Khanhng5776@ut.edu.vn",
                            PasswordHasher = "15032005",
                            UserName = "ngogiakhanh"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "dihny5348@ut.edu.vn",
                            PasswordHasher = "19072005",
                            UserName = "huynhngoyendi"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "giakhanhngo1503@gmail.com",
                            PasswordHasher = "sangyoonjin",
                            UserName = "sangyoonjin"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "yendi1907@gmai.com",
                            PasswordHasher = "yendi",
                            UserName = "yendi"
                        });
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.CareService", b =>
                {
                    b.HasOne("KoiFarmShop.Repositories.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiFarmShop.Repositories.Entities.KoiFish", "Koi")
                        .WithMany()
                        .HasForeignKey("KoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Cart", b =>
                {
                    b.HasOne("KoiFarmShop.Repositories.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.CartItem", b =>
                {
                    b.HasOne("KoiFarmShop.Repositories.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiFarmShop.Repositories.Entities.KoiFish", "Koi")
                        .WithMany()
                        .HasForeignKey("KoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.ConsignmentKoi", b =>
                {
                    b.HasOne("KoiFarmShop.Repositories.Entities.ConsignmentRequest", "ConsignmentRequest")
                        .WithMany("ConsignmentKois")
                        .HasForeignKey("ConsignmentRequestRequestId");

                    b.HasOne("KoiFarmShop.Repositories.Entities.KoiFish", "Koi")
                        .WithMany()
                        .HasForeignKey("KoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.ConsignmentRequest", b =>
                {
                    b.HasOne("KoiFarmShop.Repositories.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Customer", b =>
                {
                    b.HasOne("KoiFarmShop.Repositories.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Feedback", b =>
                {
                    b.HasOne("KoiFarmShop.Repositories.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiFarmShop.Repositories.Entities.KoiFish", "Koi")
                        .WithMany()
                        .HasForeignKey("KoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.KoiFish", b =>
                {
                    b.HasOne("KoiFarmShop.Repositories.Entities.KoiCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.OrderDetails", b =>
                {
                    b.HasOne("KoiFarmShop.Repositories.Entities.KoiFish", "Koi")
                        .WithMany()
                        .HasForeignKey("KoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiFarmShop.Repositories.Entities.Orders", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFarmShop.Repositories.Entities.Promotion", "Promotions")
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Orders", b =>
                {
                    b.HasOne("KoiFarmShop.Repositories.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoiFarmShop.Repositories.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFarmShop.Repositories.Entities.Staff", b =>
                {
                    b.HasOne("KoiFarmShop.Repositories.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
